
export const Books=[{id:1,title:"The Catcher in the Rye",Author:"J.D.Salinger",Rating:4.5,Genre:"Fiction"},
    {id:2,title:"To Kill a Mocking Bird",Author:"Harper Lee",Rating:4.8,Genre:"Fiction"},
    {id:3,title:"1984",Author:"George Orwell",Rating:4.7,Genre:"Fiction"},
    {id:4,title:"Brave New World",Author:"Aldous Huxley",Rating:4.6,Genre:"Science"},
    {id:5,title:"The Great Gatsby",Author:"F.Scott Fitzgerald",Rating:4.3,Genre:"Fiction"},
    {id:6,title:"The Faults in our stars",Author:"John Green",Rating:4.8,Genre:"Romance"},
    {id:7,title:"The Time Traveler's Wife",Author:"Audrey Niffenegger",Rating:4.5,Genre:"Romance"},
    {id:8,title:"A Brief History of Time",Author:"Stephenn Hawking",Rating:4.7,Genre:"Romance"},
    {id:9,title:"The Theory of Everything",Author:"Stephen Hawking",Rating:4.6,Genre:"Science"},
    {id:10,title:"The Hobbit",Author:"J.R.R. Tolkien",Rating:4.7,Genre:"Science"},
    {id:11,title:"Wutherings Heights",Author:"Emily Bronte",Rating:4.6,Genre:"Romance"},
    {id:12,title:"Dune",Author:"Frank Herbert",Rating:4.8,Genre:"Science"},
    {id:13,title:"The Hunger Games",Author:"Suzanne Collins",Rating:4.5,Genre:"Fiction"},
    {id:14,title:"The Alchemist",Author:"Paulo Coelho",Rating:4.8,Genre:"Fiction"},
    {id:15,title:"The NoteBook",Author:"Nicholas Sparks",Rating:4.4,Genre:"Romance"},
    {id:16,title:"Fifty Shades of Grey",Author:"E.L.James",Rating:4.2,Genre:"Romance"},
    {id:17,title:"The Martian",Author:"Andy Weir",Rating:4.8,Genre:"Science"},
    {id:18,title:"The Wrinkle in Time",Author:"Madeleine L'Engle",Rating:4.6,Genre:"Fiction"},
    {id:19,title:"The Picture of Dorian Gray",Author:"Oscar Wilde",Rating:4.5,Genre:"Fiction"},
    {id:20,title:"The Secret GArden",Author:"Frances Hodgson Burnett",Rating:4.7,Genre:"Fiction"},
    {id:21,title:"Jane Eyre",Author:"Charlotte Bronte",Rating:4.9,Genre:"Romance"},
    {id:22,title:"The Help",Author:"Kathryn Stockett",Rating:4.7,Genre:"Fiction"},
    {id:23,title:"The FAults in our Stars",Author:"John Green",Rating:4.8,Genre:"Romance"},
    {id:24,title:"The Road",Author:"cormac McCarthy",Rating:4.2,Genre:"Fiction"},
    {id:25,title:"The Science of interstellar",Author:"Kip Thorne",Rating:4.6,Genre:"Science"},
    {id:26,title:"Atlas Shrugged",Author:"Ayn Rand",Rating:4.3,Genre:"Fiction"},
    {id:27,title:"Ender's Game",Author:"Orson Scott Card",Rating:4.7,Genre:"Science"},
    {id:28,title:"The Rosie Project",Author:"Graeme Simsion",Rating:4.6,Genre:"Romance"},
    {id:29,title:"Pride and Prejudice",Author:"Jane Austen",Rating:4.9,Genre:"Romance"},
    {id:30,title:"The Lords of the Rings",Author:"J.R.R. Tolkien",Rating:4.9,Genre:"Fiction"},
];